name: Build

on:
  pull_request:

jobs:
  list-extensions:
    uses: ./.github/workflows/list-extensions.yml
    with:
      directory: extensions/

  build:
    name: Build extension ${{ matrix.extension }}
    runs-on: ubuntu-latest
    needs: list-extensions
    strategy:
      matrix:
        extension: ${{ fromJson(needs.list-extensions.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node and yarn
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Enable yarn
        run: corepack enable

      - name: Install dependencies
        run: yarn workspace ${{ matrix.extension }} install

      - name: Build extension ${{ matrix.extension }}
        run: yarn workspace ${{ matrix.extension }} run build
