name: Build

on:
  pull_request:

jobs:
  list-extensions:
    name: List extensions
    uses: ./.github/workflows/list-for-matrix.yml
    with:
      directory: extensions/

  build:
    name: Build extension ${{ matrix.extension }}
    runs-on: ubuntu-latest
    needs: list-extensions
    strategy:
      matrix:
        extension: ${{ fromJson(needs.list-extensions.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build extension ${{ matrix.extension }}
        run: npm run -w ${{ matrix.extension }} build
