name: Publish

on:
  push:
    branches:
      - main

jobs:
  list-extensions:
    name: List extensions
    uses: ./.github/workflows/list-for-matrix.yml
    with:
      directory: extensions/

  publish:
    name: Publish extension ${{ matrix.extension }}
    runs-on: ubuntu-latest
    needs: list-extensions
    strategy:
      matrix:
        extension: ${{ fromJson(needs.list-extensions.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            extensions/${{ matrix.extension }}/**
            package.json

      - name: No changes for extension ${{ matrix.extension }}
        if: steps.changed-files.outputs.any_changed == 'false'
        run: echo "No changes for extension ${{ matrix.extension }}, skipping publish steps"

      - name: Setup node and yarn
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Enable yarn
        if: steps.changed-files.outputs.any_changed == 'true'
        run: corepack enable

      - name: Install dependencies
        if: steps.changed-files.outputs.any_changed == 'true'
        run: yarn workspace ${{ matrix.extension }} install

      - name: Raycast login
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          configPath=~/.config/raycast/
          mkdir -p $configPath
          jq -n --arg accesstoken "${{ secrets.RAYCAST_TOKEN }}" '{"accesstoken": $accesstoken}' > $configPath/config.json

      - name: Build extension ${{ matrix.extension }}
        if: steps.changed-files.outputs.any_changed == 'true'
        run: yarn workspace ${{ matrix.extension }} run build

      - name: Copy raycast package.json
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          raycastApiPackageJsonDir=node_modules/@raycast/api/
          mkdir -p extensions/${{ matrix.extension }}/$raycastApiPackageJsonDir/
          cp $raycastApiPackageJsonDir/package.json extensions/${{ matrix.extension }}/$raycastApiPackageJsonDir/package.json

      - name: Publish extension ${{ matrix.extension }}
        if: steps.changed-files.outputs.any_changed == 'true'
        run: yarn workspace ${{ matrix.extension }} run publish
